require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ChairWimisController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ChairWimi. As you add validations to ChairWimi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChairWimisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all chair_wimis as @chair_wimis" do
      chair_wimi = ChairWimi.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:chair_wimis)).to eq([chair_wimi])
    end
  end

  describe "GET #show" do
    it "assigns the requested chair_wimi as @chair_wimi" do
      chair_wimi = ChairWimi.create! valid_attributes
      get :show, {:id => chair_wimi.to_param}, valid_session
      expect(assigns(:chair_wimi)).to eq(chair_wimi)
    end
  end

  describe "GET #new" do
    it "assigns a new chair_wimi as @chair_wimi" do
      get :new, {}, valid_session
      expect(assigns(:chair_wimi)).to be_a_new(ChairWimi)
    end
  end

  describe "GET #edit" do
    it "assigns the requested chair_wimi as @chair_wimi" do
      chair_wimi = ChairWimi.create! valid_attributes
      get :edit, {:id => chair_wimi.to_param}, valid_session
      expect(assigns(:chair_wimi)).to eq(chair_wimi)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ChairWimi" do
        expect {
          post :create, {:chair_wimi => valid_attributes}, valid_session
        }.to change(ChairWimi, :count).by(1)
      end

      it "assigns a newly created chair_wimi as @chair_wimi" do
        post :create, {:chair_wimi => valid_attributes}, valid_session
        expect(assigns(:chair_wimi)).to be_a(ChairWimi)
        expect(assigns(:chair_wimi)).to be_persisted
      end

      it "redirects to the created chair_wimi" do
        post :create, {:chair_wimi => valid_attributes}, valid_session
        expect(response).to redirect_to(ChairWimi.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved chair_wimi as @chair_wimi" do
        post :create, {:chair_wimi => invalid_attributes}, valid_session
        expect(assigns(:chair_wimi)).to be_a_new(ChairWimi)
      end

      it "re-renders the 'new' template" do
        post :create, {:chair_wimi => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chair_wimi" do
        chair_wimi = ChairWimi.create! valid_attributes
        put :update, {:id => chair_wimi.to_param, :chair_wimi => new_attributes}, valid_session
        chair_wimi.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested chair_wimi as @chair_wimi" do
        chair_wimi = ChairWimi.create! valid_attributes
        put :update, {:id => chair_wimi.to_param, :chair_wimi => valid_attributes}, valid_session
        expect(assigns(:chair_wimi)).to eq(chair_wimi)
      end

      it "redirects to the chair_wimi" do
        chair_wimi = ChairWimi.create! valid_attributes
        put :update, {:id => chair_wimi.to_param, :chair_wimi => valid_attributes}, valid_session
        expect(response).to redirect_to(chair_wimi)
      end
    end

    context "with invalid params" do
      it "assigns the chair_wimi as @chair_wimi" do
        chair_wimi = ChairWimi.create! valid_attributes
        put :update, {:id => chair_wimi.to_param, :chair_wimi => invalid_attributes}, valid_session
        expect(assigns(:chair_wimi)).to eq(chair_wimi)
      end

      it "re-renders the 'edit' template" do
        chair_wimi = ChairWimi.create! valid_attributes
        put :update, {:id => chair_wimi.to_param, :chair_wimi => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested chair_wimi" do
      chair_wimi = ChairWimi.create! valid_attributes
      expect {
        delete :destroy, {:id => chair_wimi.to_param}, valid_session
      }.to change(ChairWimi, :count).by(-1)
    end

    it "redirects to the chair_wimis list" do
      chair_wimi = ChairWimi.create! valid_attributes
      delete :destroy, {:id => chair_wimi.to_param}, valid_session
      expect(response).to redirect_to(chair_wimis_url)
    end
  end

end
