require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TimeSheetsController, type: :controller do
  before(:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
    @project = FactoryGirl.create(:project)
  end

  # This should return the minimal set of attributes required to create a valid
  # TimeSheet. As you add validations to TimeSheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {month:1, year:2015, salary:100, salary_is_per_month:false,
      workload:100, workload_is_per_month: true, user_id:@user.id,
      project_id:@project.id}
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimeSheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #edit" do
    it "assigns the requested time_sheet as @time_sheet" do
      time_sheet = TimeSheet.create! valid_attributes
      get :edit, {:id => time_sheet.to_param}, valid_session
      expect(assigns(:time_sheet)).to eq(time_sheet)
    end
  end
end
